### ISSUE TITLE
RAZ_ReverseShell nc.exe was not found

### ISSUE THREAD

**Issue by JuicySword** [hak5/bashbunny-payloads#102]
@ralphyz 
where do i get the nc.exe and where will I put it ?

**Comment by surrealalucard** [comment]
I grabbed mine from the [nmap](https://nmap.org/download.html) site. Grab the up-to-date command line one, and I had to include two .dll files inside the switch dir to get it to work.

**Comment by ralphyz** [comment]
I get mine from kali linux - just `locate nc.exe`
