### ISSUE TITLE
Chrome Path is Wrong

### ISSUE THREAD

**Issue by opticon** [hak5/bashbunny-payloads#122]
As of 10.9.5, the default path for Chrome's goodies is not where the script directs us: /Library/Application\\ Support/Google/Chrome/Default/Cookies
The correct path is as follows:/Library/Application\\ Support/Google/Chrome/Profile/Cookies

Here's the rub- that cute little "Profile" folder always has a number associated with it; Profile 2 , Profile 3 etc. If the variable could be set to download the payload of said Profile folder then it should work. I don't know how to write the code. Help me make this better for all of us!

**Comment by mike111b** [comment]
Are you looking at a specific payload here?  if so which one?

**Comment by opticon** [comment]
Thank you so much for replying to me! The payload is called Mac Info Grabber. In fact, if I don't comment out the lines: /Library/Application\ Support/Google/Chrome/Default/Cookies [and]
/Volumes/BashBunny/$lootdir/chromecookies.db.... It won't grab anything! If I knew what I was doing, I could rewrite the code to grab specific documents from multiple directories, but I don't know how to write that; Desktop, Documents, Pictures, Downloads, etc.

Thank you in advance for your help. I can't express how much I appreciate it.

-Cheers!

**Comment by markwbrown** [comment]
I second this -- Chrome 56.0.2924.87 stores the Cookie db file in ~/Users/*username*/Library/Application\ Support/Google/Chrome/Default

**Comment by opticon** [comment]
@markwbrown I appreciate your reply, but you restated the path that leads to the "Default" folder, which does not exist on any of my installs. The correct path to cookies on all of my Macs is as follows: ~/Users/username/Library/Application\\ Support/Google/Chrome/Profile\\ 2/Cookies

Have a look around your system and verify that there exists a Profile folder.

=Cheers!

**Comment by markwbrown** [comment]
@opticon Nope, ~/Users/username/Library/Application\ Support/Google/Chrome/ does not contain a Profile or numbered profile folder. Which version of chrome are you using?

**Comment by mike111b** [comment]
As seb has labeled, this is a payload bug.  Chrome can have any number of profiles including Default.  By default during Chrome install you get a Chrome user called "Default".  When you make more users their profiles are pointed at Profile 1, Profile 2, Profile 3.

**Comment by opticon** [comment]
Thanks @TheRealNoob for understanding what I was referring to, as well replying to my comment. What would the script look like if one were to look for the Cookies file within three profile folders only? It should't go beyond 3. Lastly, and unrelated to the cookies, I want to extract data from multiple sources on a Mac. I've copy and pasted the entire segment of code, but was curious if there was a single line of code that I should be using, rather than a segment, and add Desktop, Pictures, Downloads, etc. Thanks in advance.

**Comment by TheRealNoob** [comment]
@opticon 
I can't speak for unix, but I have finished rewriting a Chrome script for Windows.  Specifically a script that targets the database storing usernames/passwords for website logins. [This one.](https://github.com/sekirkity/BrowserGather/blob/master/BrowserGather.ps1)  It's not done just quite yet, the author and I still have a few details to work out.  The same author also wrote a script for cookies and I plan on helping him out with that script next.  There isn't a whole lot of difference between bash and powershell syntax, so you could probably take a look at my scripts once they go up in a week or so.  But if you really want to get into modifying your own payloads I would suggest that you learn bash yourself.
