### ISSUE TITLE
Ducky attacks failing

### ISSUE THREAD

**Issue by xillwillx** [hak5/bashbunny-payloads#13]
due to the bash interpreting QUACK textfiles/commands literally, if you have bash special characters in your commands the ducky attack will fail. Need to escape the special chars.

**Comment by honourity** [comment]
#17

**Comment by honourity** [comment]
#17

**Comment by sebkinne** [comment]
I  think that this is pretty much expected behavior when you call the Q/UACK command via Bunny Script. If you wanted to avoid any escaping, calling Q/UACK <filename.txt> will read the file directly therefore eliminating the need to escape characters first.
