### ISSUE TITLE
Common settings file would be helpful

### ISSUE THREAD

**Issue by targetdrone** [hak5/bashbunny-payloads#142]
I'm already seeing divergence in payloads where each author has to figure out how to do things their own way.  Loot stored in switch folders, random colors and blink rates for various steps, and different quacks for different locales.  Now that there is a growing body of really cool payloads, this is probably a good time to learn from these lessons.  I'd like to propose a common settings file, perhaps loaded in by bunnyhelper.sh, that would give developers the assistance they need.

The file would contain the following:  

- A generated $loot directory name, perhaps based on the target machine's name and an increasing sequence number, since the bunny has no RTC to provide an accurate date. Maybe it could incorporate an engagement identifier for the pen tester to tag all related tests.
- Defined colors by attack stage.  There has already been a pull request for a payload helper that substitutes text names for color codes.  Instead of making the tester remember "is this attack done if the light is off, or if the light is green?", there could be a list of attack stages or phases.  The attacker would simply include `LED RECON` when the attack enters the recon phase.  (Note these colors and phases are totally arbitrary and imaginary, I'd love someone to replace them with something better):
 * INIT - Solid white light indicating the payload is preparing for the attack
 * RECON - Solid amber light indicating the payload is actively probing the client
 * EXFIL - Solid purple light indicating the loot is being transmitted
 * DONE - Solid green light indicating the payload has been delivered and exfiltration is complete.
 * USER_INPUT_NEEDED - flashing amber light indicating the tester needs to do something
 * ERROR - Solid red light indicating the script encountered an error and the test has been stopped.
- Locale specific quacks:  A German machine will expect an `<alt>+J` to dismiss UAC, while an English machine will expect an `<alt>+Y` to do the same thing.  Putting these common quacks in a config file would let a tester define the language, instead of each payload's author.

I'm sure there are other lessons to be learned from the payloads that have been created so far, too, so this list isn't exhaustive by any means.  But just getting payload authors used to bringing in some standardized stuff would go a long way to helping the testers in the field.

**Comment by sebkinne** [comment]
I think with firmwares v1. 1 and v1. 2 this issue is probably satisfied. 

We'll be adding more defaults to the config file throughout further development.
