### ISSUE TITLE
Extensions folder

### ISSUE THREAD

**Issue by GitGitBunny** [hak5/bashbunny-payloads#171]
Hey all!

I like the new 1.1 structure of creating enhancements, it can be used for creating a specific loot folder.. doing several fun stuff like for example start up an apache server, etc.

But it would be nice if we could share eachothers idea of generic functions, so i would like to have a folder to share extensions as well. I couldn't find the folder on this git.

**Comment by GitGitBunny** [comment]
Let me change that! Can we put it one layer up? So the structure will be 
| - extensions
| - library
| - switch1
| - switch2

**Comment by tuzzmaniandevil** [comment]
:+1:

**Comment by sebkinne** [comment]
I had made this suggestion to Darren, but he wanted to keep them in the payloads folder. 

If we do want to change it, we'll have to have some checks in the framework that will remove the old path and possibly import custom extensions.

If we get some more votes to move the directory, we'll respect the communities wishes of course :)

**Comment by hak5darren** [comment]
👍

**Comment by sebkinne** [comment]
And @hak5darren has spoken with emoji. This change will be in 1.2, thank you!
