### ISSUE TITLE
Windows newline support

### ISSUE THREAD

**Issue by St0ner1995** [hak5/bashbunny-payloads#183]
More of a suggestion really but may i suggest running payload.txt through either of the following before execution?

`cat $payloadfile | dos2unix -U > /tmp/payload.sh && chmod +x /tmp/payload/sh && /tmp/payload.sh`

`cat $payloadfile | sed 's/\r$//' > /tmp/payload.sh && chmod +x /tmp/payload/sh && /tmp/payload.sh`

`tr -d '\r' < $payloadfile > /tmp/payload.sh && chmod +x /tmp/payload.sh && /tmp/payload.sh`

**Comment by sebkinne** [comment]
Hi, 

This actually already happen in the bunny_framework. I assume you are talking about the issues Darren was having?

If so, this was for a bunny extension which should always be written without carriage returns. We might extend the framework to automatically fix other included files, but for now escaping the bunny payloads should be fine.
