### ISSUE TITLE
Additional Ethernet attack modes

### ISSUE THREAD

**Issue by Altecheon** [hak5/bashbunny-payloads#194]
The current Ethernet modes are situated behind being faster than the current internet adapters, however doing so tends to cause the target machine to loose connectivity.

Is it possible to add a feature that would set the bunny to have say a dialup connection to allow for attacks to function without dropping internet connectivity.  

An example of when this could be helpful is when a has a large amount of data to pull. And the user comes back, you could collect the bunny at another time without the user visibly having connectivity issues.

Another would be when you are using a domain account that you have recovered the password for to attack a machine, however the account is not cached and needs to connect to the domain controller to authenticate. If the connection to the domain is available still, the attack would be possible. As it stands you won't be able to connect to the domain to authenticate.

**Comment by sebkinne** [comment]
This feature was added to the Bash Bunny in firmware v1.3 :)
