### ISSUE TITLE
[Idea] Super stealthy exfil method

### ISSUE THREAD

**Issue by Vinc0682** [hak5/bashbunny-payloads#196]
I recently had an idea for a super stealthy exfil method and maybe some of you are able to implement it 😄 

1. The bash bunny registeres itself as network printer.

2. The target prints everything.

Alternatively (for bigger files), you can try:

1. The bunny fires up an hostspot (as in UndercoverBunny)

2. An external device (like an RaspberryPi connects to the hotspot and registeres itself as network printer)

3. The bunny launches a script waiting for the Raspi to connect and then print's everything.

The alternative may (or may not) be executed with a RubberDucky instead of a BashBunny.

**Comment by sebkinne** [comment]
Hi @Vinc0682,

Why don't you make this suggestion on the [Hak5 Forums](https://forums.hak5.org/index.php?/forum/93-payloads/)? They are usually a lot more active :)

Because this isn't really an issue, I'll close this for now.
