### ISSUE TITLE
RAZ_ReverseShell file not found

### ISSUE THREAD

**Issue by crunchy234** [hak5/bashbunny-payloads#197]
I keep getting the file not found error (blue flashing) when trying to run the RAZ_ReverseShell script.

I have sshed into the bunny and I do not see anything in ```/root/udisk```
I ran the following in the bunny in switch mode 3 connecting using screen:
```
Linux bunny 3.4.39 #130 SMP PREEMPT Fri Feb 10 14:24:25 CST 2017 armv7l
           _____  _____  _____  _____     _____  _____  _____  _____  __ __ 
 (\___/)  | __  ||  _  ||   __||  |  |   | __  ||  |  ||   | ||   | ||  |  |
 (='.'=)  | __ -||     ||__   ||     |   | __ -||  |  || | | || | | ||_   _|
 (")_(")  |_____||__|__||_____||__|__|   |_____||_____||_|___||_|___|  |_|  
 Bash Bunny by Hak5     USB Attack/Automation Platform      

root@bunny:~# ls 
ATTACKMODE  LICENSE.txt  bash_bunny.sh      ducklog.txt  tools
EULA.txt    Q            bootcount          g_ether.ko   udisk
LED         QUACK        do_post_update.sh  private      version.txt
root@bunny:~# ll udisk/
total 8
drwxr-xr-x 2 root root 4096 Feb  9  2017 ./
drwx------ 6 root root 4096 Dec 31 16:00 ../
root@bunny:~# 
```

I also found that the payload script was run in /tmp do all the other files in the switch folder get coppied to /tmp when said switch is active?

**Comment by Altecheon** [comment]
Found it somewhere in the forums a while ago. The udisk folder is not always mounted, whether or not to keep it mounted will be decided in the future. You can mount it from /dev/nandf I believe. The following command can be used from the folder containing udisk to mount it.
mount /dev/nandf udisk/

**Comment by ralphyz** [comment]
you need to place the nc.exe file in the switch folder with the payload.txt file.  Get it from Kali
`locate nc.exe`
or get it from nmap's website:
`https://nmap.org/ncat/`
