### ISSUE TITLE
Feature Request: Keyboard for ES (ISO)

### ISSUE THREAD

**Issue by bntzio** [hak5/bashbunny-payloads#237]
I'm from Mexico, and the keyboards here are Spanish ISO (Latin) so my BashBunny isn't working here, I got a working `.properties` file for the Rubber Ducky keyboard, but that is not the expected format for the BB.

Any plans of doing this keyboard? I'd like to help but need to know how. I've been searching but no clues.

Thanks!

**Comment by bntzio** [comment]
@hak5darren any news?

**Comment by sebkinne** [comment]
Hi @bntzio,

You will need to create a json file that contains the language definition. You can find examples of how to create such a file here: https://github.com/hak5/bashbunny-payloads/tree/master/languages

Once you have created this file, please send a Pull Request our way, and we'll ensure it's included.
