### ISSUE TITLE
Update payloads to support 1.1+

### ISSUE THREAD

**Issue by sundhaug92** [hak5/bashbunny-payloads#248]
# Don't set DUCKY_LANG in payloads (see [Version 1.2 changelog](https://storage.googleapis.com/bashbunny_updates/ch_fw_1.2-changelog.txt))
- [x] [Incident_Response/Hidden_Images/payload.txt](https://github.com/hak5/bashbunny-payloads/blob/master/payloads/library/Incident_Response/Hidden_Images/payload.txt)
- [x] [Incident_Response/Link File analysis/payload.txt](https://github.com/hak5/bashbunny-payloads/blob/master/payloads/library/Incident_Response/Link%20File%20analysis/payload.txt)
- [x] [recon/Link File analysis/payload.txt](https://github.com/hak5/bashbunny-payloads/blob/master/payloads/library/recon/Link%20File%20analysis/payload.txt)
- [x] [credentials/SudoBackdoor/cleaner/payload.txt](https://github.com/hak5/bashbunny-payloads/blob/master/payloads/library/credentials/SudoBackdoor/cleaner/payload.txt)
- [x] [credentials/SudoBackdoor/injector/payload.txt](https://github.com/hak5/bashbunny-payloads/blob/master/payloads/library/credentials/SudoBackdoor/injector/payload.txt)
- [x] [prank/win93/payload.txt](https://github.com/hak5/bashbunny-payloads/blob/master/payloads/library/prank/win93/payload.txt)
- [x] [remote_access/Win_x64_JS_Rev_Meter/payload.txt](https://github.com/hak5/bashbunny-payloads/blob/master/payloads/library/remote_access/Win_x64_JS_Rev_Meter/payload.txt)

# Don't reference bunny_helpers.sh (see [Version 1.1 changelog](https://storage.googleapis.com/bashbunny_updates/ch_fw_1.1-changelog.txt))
- [x] [exfiltration/Powershell_TCP_Extractor/payload.txt](https://github.com/hak5/bashbunny-payloads/blob/master/payloads/exfiltration/Powershell_TCP_Extractor/payload.txt)
- [x] [exfiltration/ftp_exfiltrator/payload.txt](https://github.com/hak5/bashbunny-payloads/blob/master/payloads/exfiltration/ftp_exfiltrator/payload.txt)
- [x] [general/ExecutableInstaller/payload.txt](https://github.com/hak5/bashbunny-payloads/blob/master/payloads/general/ExecutableInstaller/payload.txt)
- [x] [remote_access/NothingLess/payload.txt](https://github.com/hak5/bashbunny-payloads/blob/master/payloads/remote_access/NothingLess/payload.txt)
- [x] [exfiltration/BlackBackup/payload.txt](https://github.com/hak5/bashbunny-payloads/blob/master/payloads/exfiltration/BlackBackup/payload.txt)
- [x] [exfiltration/FileInfoExfil/payload.txt](https://github.com/hak5/bashbunny-payloads/blob/master/payloads/exfiltration/FileInfoExfil/payload.txt)
- [x] [sFTP Directory Grabber/payload.txt](https://github.com/hak5/bashbunny-payloads/blob/master/payloads/sFTP%20Directory%20Grabber/payload.txt)
- [x] [credentials/WifiGrabber/payload.txt](https://github.com/hak5/bashbunny-payloads/blob/master/payloads/credentials/WifiGrabber/payload.txt)
- [x] [prank/RickRoll/payload.txt](https://github.com/hak5/bashbunny-payloads/blob/master/payloads/prank/RickRoll/payload.txt)
- [x] [recon/PrivEscChecker/payload.txt](https://github.com/hak5/bashbunny-payloads/blob/master/payloads/recon/PrivEscChecker/payload.txt)
- [x] [android/fireytv/payload.txt](https://github.com/hak5/bashbunny-payloads/blob/master/payloads/android/fireytv/payload.txt)
- [x] [credentials/BruteBunny/payload.txt](https://github.com/hak5/bashbunny-payloads/blob/master/payloads/credentials/BruteBunny/payload.txt)
- [x] [remote_access/WindowsMeterpreterStaged/payload.txt](https://github.com/hak5/bashbunny-payloads/blob/master/payloads/remote_access/WindowsMeterpreterStaged/payload.txt)
- [x] [general/Proxy_Interceptor/payload.txt](https://github.com/hak5/bashbunny-payloads/blob/master/payloads/general/Proxy_Interceptor/payload.txt)
- [x] [credentials/DumpCreds/payload.txt](https://github.com/hak5/bashbunny-payloads/blob/master/payloads/credentials/DumpCreds/payload.txt)

**Comment by thehappydinoa** [comment]
Fixed in [pull request](https://github.com/hak5/bashbunny-payloads/pull/274).

**Comment by sundhaug92** [comment]
Updated presuming #274

**Comment by sundhaug92** [comment]
Note, this list missed out on some files (due to spaces in filenames and other fun things)

**Comment by sebkinne** [comment]
Closing due to #277 - thanks!
