### ISSUE TITLE
top uses 100% cpu usage. 

### ISSUE THREAD

**Issue by kenthinson** [hak5/bashbunny-payloads#253]
If connection to the bunny over tty then running top I see that the program top itself its using 100% cpu. also the bunny gets very hot very fast. If the bunny is plugged into usb 2.0 port on my computer the bunny will freeze and crash. if the bunny is plugged into usb 3.0 port it will keep running for a undefined amount of time.

**Comment by sebkinne** [comment]
Sorry @kenthinson I can't confirm this behavior. Have you reset your BB?
