### ISSUE TITLE
Missing keys in no.json caused by bug in QUACK

### ISSUE THREAD

**Issue by fiveonine** [hak5/bashbunny-payloads#258]
Special keys like æ ø and å is missing from no.json and dk.json. QUACK is unable to read æ ø and å from script files and responds width this error after my attempt to add the keys to .json file

>Traceback (most recent call last):
  File "/usr/local/bunny/bin/QUACK", line 182, in <module>
    run_script(input_line, language)
  File "/usr/local/bunny/bin/QUACK", line 158, in run_script
   context = run_ducky_line(context, line, lang_file)
  File "/usr/local/bunny/bin/QUACK", line 82, in run_ducky_line 
    elements = lang_file[char].split(",");
KeyError: '\xc3'

*The bunny is also reluctant to accept special characters over serial and ssh.*

**Comment by fiveonine** [comment]
Update:
The issue is in how python reads the characters.

**Comment by B2Crypt** [comment]
Found a solution here yet? I got the same issue as well.

**Comment by fiveonine** [comment]
made a [fix](https://github.com/fiveonine/BashBunny) where i modified the QUACK script to make it unicode compliant, its not perfect but it works.

**Comment by sebkinne** [comment]
@fiveonine are there any bugs with your fix? If this works without regression we'll roll it into the next firmware update.

**Comment by fiveonine** [comment]
I have not done extensive  testing but it works fine without any bugs on my BashBunny.

**Comment by sebkinne** [comment]
Thanks for the information - we'll roll UTF-8 support into the next firmware.
