### ISSUE TITLE
PT Language file for Mac OSX

### ISSUE THREAD

**Issue by naagodinho** [hak5/bashbunny-payloads#286]
Hi all, I've updated a few keys that were not correctly configured in the PT language file when using a Portuguese Mac keyboard. It still misses a few special characters that can be used, specially the c cedilla: Ç

See file attached with the changes

[pt.json.zip](https://github.com/hak5/bashbunny-payloads/files/1441759/pt.json.zip)

**Comment by naagodinho** [comment]
Another update for the @, {} and  [] chars in the Mac. Note that the PT keyboard needs a space after the ~ char. Explanation:  

US keyboard this works: QUACK STRING find \~ -name \'*.pdf\'
PT keyboard this works: QUACK STRING find \~ \ -name \'*.pdf\'

[pt_MACOS.json.zip](https://github.com/hak5/bashbunny-payloads/files/1441917/pt_MACOS.json.zip)

**Comment by sebkinne** [comment]
Hi there,

Please feel free to send any fixes via a PR :)
