### ISSUE TITLE
having Issues with payload

### ISSUE THREAD

**Issue by urlordjames** [hak5/bashbunny-payloads#314]
I'm using the payload [QuickCreds](https://github.com/hak5/bashbunny-payloads/tree/master/payloads/library/credentials/QuickCreds) and I'm having issues getting it to work, I installed responder on the BashBunny and it's in the right folder, getting FAIL2, not sure what Target did not aquire IP address means.  Sorry I'm new.

**Comment by urlordjames** [comment]
Now that I checked, safely ejecting it and removing it from my computer deletes the responder folder for some reason.

**Comment by urlordjames** [comment]
I'm going to try an update it, this may fix my problem.

**Comment by urlordjames** [comment]
turns out I'm actually an idiot, I didn't install the tool correctly, mistook FAIL1 for FAIL 2, and made a fool of myself on Github for everyone to see.  I think there's a lesson here...

**Comment by thehappydinoa** [comment]
Lol we all have our moments I'm glad you figured it out
