### ISSUE TITLE
GET SWITCH_POSITION not working 

### ISSUE THREAD

**Issue by thehappydinoa** [hak5/bashbunny-payloads#324]
While running GET SWITCH_POSITION in ssh I am able to get the variable:
```bash
root@bunny:~# GET SWITCH_POSITION
root@bunny:~# echo $SWITCH_POSITION
switch3
```
But when using the new `WAIT` extension I realized that when running an attack I could not get `$SWITCH_POSITION`. `WAIT` would not wait and completely skip the line (@hak5darren). I am also running `1.5_298` (@sebkinne)

My code is as follows:
```bash
GET SWITCH_POSITION
TEST=$SWITCH_POSITION
ATTACKMODE HID
Q STRING Test: $TEST and SWITCH_POSITION: $SWITCH_POSITION
```
This results in `Test: and SWITCH_POSITION:` which is not a great response.

Any help would be greatly appreciated.

**Comment by GermanNoob** [comment]
Hi there,
I tried the following code which works fine. So I think you just have to use some quotation marks...

`LED SETUP
GET SWITCH_POSITION

LED ATTACK
ATTACKMODE HID
sleep 3 
RUN OSX textedit
Q STRING 'This is position of switch: '$SWITCH_POSITION

LED FINISH`

**Comment by thehappydinoa** [comment]
Huh ok
