### ISSUE TITLE
MacOS (French) HID Keyboard language

### ISSUE THREAD

**Issue by FlorianTousch** [hak5/bashbunny-payloads#357]
All in the title.
I can't find Json file for macOS keyboard.
Is it existing or I need to create one?

**Comment by mattlawer** [comment]
I had to make my own:
https://gist.github.com/mattlawer/c733122b762e68c9ebb8b9f7ddaea0f6

Also made the .properties file for the Rubber Ducky:
https://gist.github.com/mattlawer/16a74e6241216376969908158837bf2f

I hope this will help.
