### ISSUE TITLE
Control C

### ISSUE THREAD

**Issue by ilovebashbunny** [hak5/bashbunny-payloads#363]
Can someone pls tell me how to make a copy-paste on bash bunny?
if i type Q CTRL C nothing happens, same with CONTROL C or CTL C
i think there is a easy way to do this, i havent just found it out jet

**Comment by NickRaw** [comment]
Try CTRL C

**Comment by ilovebashbunny** [comment]
Without a Q in fronnt of it?
Ok i will try

**Comment by ilovebashbunny** [comment]
Ok i ve solved it by myself. CTRL INSERT is for copy, and SHIFT INSERT is paste. But i still dont know how to do CTRL A
