### ISSUE TITLE
The term "sleep1" is not recognized - Wallpaper changer

### ISSUE THREAD

**Issue by jcardonne** [hak5/bashbunny-payloads#393]
Hello, I am writing to you because the wallpaper change does not work for me. When the "powershell" is still open it displays an error message: 
```
`sleep1 : Le terme «sleep1» n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou programme
exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès est correct
et réessayez.
Au caractère Ligne:1 : 193
+ ... .EXE USER32.DLL,UpdatePerUserSystemParameters , 1,True;sleep1} while( ...
  ~~~~~~
    + CategoryInfo          : ObjectNotFound: (sleep1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`
```

This is in french, the translation is: 
```
The term "sleep1" is not recognized as a command applet name, function, script file or program
executable. Check the spelling of the name, or if a path exists, check that the path is correct
and try again.
```

How can I fix it ?
Thanks you

**Comment by WatskeBart** [comment]
Put a space between sleep and 1 e.g. `sleep 1` not `sleep1`

**Comment by jcardonne** [comment]
Thank you very much, I managed to rewrite the script, without errors. Indeed I had a lot of mistakes and the script coming from the librairy didn't work.
[https://forums.hak5.org/topic/49303-rewriting-of-wallpaper-changer-of-doom/](https://forums.hak5.org/topic/49303-rewriting-of-wallpaper-changer-of-doom)
