### ISSUE TITLE
How to use the payload with french keyboard language?

### ISSUE THREAD

**Issue by bolieu85** [hak5/bashbunny-payloads#403]
Hi!

I'm using a WHID and wanted to know how it could possible to use french language characters aka
é î ç à è   

because at the moment, when typing the string, numbers appear instead of those characters.

thanks!

**Comment by 95ImadEL** [comment]
by typing in the payload : 

DUCKY_LANG fr

**Comment by bolieu85** [comment]
thx!

and where do I find this config.txt  doc in the rubberducky?

thx again

**Comment by 95ImadEL** [comment]
This config.txt is in the bash bunny, for the rubber ducky, i think you should while using the encode script, you should specify language as follow :

$java -jar duckencode.jar -i script.txt -o inject.bin -l fr
