### ISSUE TITLE
Quick Cred Fail vs Firmware Recovery

### ISSUE THREAD

**Issue by mathew-fleisch** [hak5/bashbunny-payloads#42]
Just a general suggestion...
My bunny already went through a recovery cycle and it blinks the led red for a couple of minutes during that time. Shortly after that recovery was successful, I was trying out quick creds, which also uses a blinking red led to show failure. I waited a good ten minutes to make sure it wasn't going through a recovery mode before I unplugged it, because of the double use of the error state. I think that the recovery mode blink should be some sort of pattern (like morse code 'sos') to differentiate it from a standard blinking red light, that might be frequently used in these payloads.

**Comment by sebkinne** [comment]
@mathew-fleisch I agree - I'll see what I can do.

**Comment by mathew-fleisch** [comment]
I think the new firmware fixes this issue.

**Comment by sebkinne** [comment]
Sure does :)
