### ISSUE TITLE
No Bash Bunny

### ISSUE THREAD

**Issue by imABitSpecial** [hak5/bashbunny-payloads#459]
I'm wondering if there is a way to use payloads without a Bash Bunny. I tried to buy one but the total ended up being 2.2 times the original price.

**Comment by dallaswinger** [comment]
Unfortunately, Bash Bunny payloads require a Bash Bunny.

**Comment by user421921** [comment]
If you want a $10 bashbunny that has mouse functions, and a lot of extra
sick features look into the P4wnP1 aloa
