### ISSUE TITLE
macinfograbber completely broken

### ISSUE THREAD

**Issue by audibleblink** [hak5/bashbunny-payloads#47]
`~`s resolve to `root`, not current user on macOS

paths resolve with double dashes `//`

~volume doesn't mount as /Volumes/BashBunny~

lootdir points to nonexistent path

__Edit__: After speaking with other users, stock BBs do mount as `/Volume/BashBunny`. My bad.

**Comment by audibleblink** [comment]
<img width="567" alt="image" src="https://cloud.githubusercontent.com/assets/4605783/23839209/c939e5b4-0772-11e7-85fb-7c8971b72c9d.png">

**Comment by audibleblink** [comment]
@bobmcdouble3 wanna take a look?

**Comment by eliddell1** [comment]
It worked for me except I had to  escape the space in /Application Support/ to /Application\ Support/

**Comment by eliddell1** [comment]
I take that back.. it is giving me a permission denied when trying to > to the loot directory

**Comment by audibleblink** [comment]
@eliddell1 lines 27 and 30 type as `~/Library...` and `~/Documents`?

Both type out as `/root/Libray...` and `/root/Documents` which don't exist on macOS

**Comment by eliddell1** [comment]
I have it working..  with modifications...  See my comment in https://forums.hak5.org/index.php?/topic/40363-maclinux-~-root/

**Comment by audibleblink** [comment]
want to submit the PR to fix it in the repo?

**Comment by eliddell1** [comment]
Fyi in onus on the forum

**Comment by sebkinne** [comment]
Fixed
