### ISSUE TITLE
BB is slow to bind sockets in ECM_ETHERNET mode

### ISSUE THREAD

**Issue by audibleblink** [hak5/bashbunny-payloads#57]
While developing a payload that creates a webserver on the BB, I noticed it takes 12+ seconds for any request to bind a port on the BB.

Using ECM_ETHERNET attack mode and sshing in, all of the following command are affected:

```sh
python -m SimpleHTTPServer 8888
nc -nvlp 8888
ruby -run -e httpd . -p 8888
```

These same commands work as expected (sub 1 second response) when connected to the bunny in serial mode.

Creating a payload that starts the server on the bunny and then uses HID to make the victim curl the bunny fails because the server hasn't bound to the socket yet.

Recording of the issue - https://asciinema.org/a/arrd1giatg2w5gb8bme0ct7py

**Comment by TorreyBetts** [comment]
I tested out the python server on my BB and it loads in 1 second compared to your long wait.

https://www.dropbox.com/s/h56rbpezzlg3vgu/Screen%20Record2017-03-14%2022_09_07.mov?dl=0

Before I started recording, I plugged in the BB, SSH'd in and type clear before doing the server command.

**Comment by audibleblink** [comment]
Closing issue as this seems to be just me. 
https://forums.hak5.org/index.php?/topic/40416-slow-at-binding-sockets/#comment-287875
