### ISSUE TITLE
nmap returns dummy mac address

### ISSUE THREAD

**Issue by IMcPwn** [hak5/bashbunny-payloads#6]
All of my nmap scans on multiple computers (ECM_ETHERNET and RNDIS_ETHERNET) return:
```
MAC Address: 00:11:22:33:44:55 (Cimsys)
```

for the mac address. What is going on here?

**Comment by be3n** [comment]
the attack is not coming in over the physical network interface, but the "fake" bunny interface so that is why you are seeing a made up MAC.  i don't think this can be fixed. (at least not with this attack)

**Comment by panicacid** [comment]
Does that mean the nmap scan is of the "fake" network and not the "victim"?

**Comment by sebkinne** [comment]
This is correct. You are scanning the host machine and therefore all results will be for the bunny's interface only. This also means that if a service is bound to an IP other than 0.0.0.0, it will also not show up. 

This is unfortunately unavoidable, at least when we are not pivoting through the host somehow.
