### ISSUE TITLE
Possibility to set attackmode to read-only storage

### ISSUE THREAD

**Issue by IMcPwn** [hak5/bashbunny-payloads#9]
Would it be possible to set the attackmode to read-only storage for computers that will scan/delete files on the storage partition automatically so your payload or other files don't get deleted?

**Comment by WatskeBart** [comment]
Curious about this as well

**Comment by honourity** [comment]
Wonder if we could spoof vid/pid of a cd-r drive.
I looked at [http://www.linux-usb.org/usb.ids](http://www.linux-usb.org/usb.ids)

I tried `ATTACKMODE STORAGE VID_0X0644 PID_0X1000`

But in device manager i get  "Unknown USB Device (Configuration Descriptor Request Failed)"
It does seem that the vid/pid is successfully spoofed, except there seems to be more missing still. Sorry I don't know much about this kind of pid stuff.

So maybe we need a little more documentation and/or flexiblity on spoofing device descriptors if its possible?

**Comment by sebkinne** [comment]
This is actually much easier as it's a simple option set when loading the kernel module. We'll add support into the framework for this with the next release.

**Comment by IMcPwn** [comment]
Thanks Seb!

**Comment by sebkinne** [comment]
I'll close this as the feature was baked into fw v1.2.
