### ISSUE TITLE
Meta: Pull request merges

### ISSUE THREAD

**Issue by judge2020** [hak5/bashbunny-payloads#95]
Currently, when merging Pull Requests, the changes are "merged" by the collaborators, however, the commits by their original authors are not preserved and therefore not given credit.

Example: Merge PR from mrt0mat0 ([here](https://github.com/hak5/bashbunny-payloads/commit/1e8406bc38d11bfff4408ff22ac6919d3ab023fe))

@mrt0mac0's changes are merged into the main repo, however, he is not credited with the commit.

My proposal: instead of merging changes, choose "rebase and merge". This will preserve the original author's commits and give them credit in the commit history.

**Comment by sebkinne** [comment]
Hi @judge2020 - this is actually incorrect. While a merge will show the merge as a commit, the actual commits are absolutely present.

For the merge you provided, you can see his commits 70af3218 and 00684c8. This user configured his Git client to a different name than their username, so the name is not linked. This is something the merge actually fixes, as it gives extra credit based on the Github user.
