### ISSUE TITLE
Submitting Payload?

### ISSUE THREAD

**Issue by 0xCoto** [hak5/bashbunny-payloads#97]
Hi there,

I haven't been able to figure out how to actually submit a Payload to the Bash Bunny repository... I haven't been able to submit a Pull Request (if that's even the way you're supposed to submit your written payload).

Anyway, if someone could please upload my Payload for me, that'd be great: https://github.com/0xCoto/bashbunny-payloads/tree/master/payloads/library/DuckyTemplate

Thank you. :)

**Comment by sebkinne** [comment]
Hi @0xCoto please take a look at the Hak5 video detailing how to do this: https://youtu.be/H6z9BXevsZg
